# Generated by Django 5.2.6 on 2025-09-16 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.CharField(max_length=700)),
                ('url', models.URLField()),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Sermon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=700)),
                ('url', models.URLField(default='https://www.youtube.com/watch?v=sjkrrmBnpGE&t=11s')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
