# Generated by Django 5.2.6 on 2025-10-24 15:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Enter the title of the announcement', max_length=200)),
                ('content', models.TextField(help_text='Enter the content of the announcement')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='Congregational meeting', help_text='Enter the name of the event', max_length=200)),
                ('description', models.CharField(help_text='Enter a brief description of the event', max_length=700)),
                ('flyer', models.ImageField(default='event_flyers/default_profile.jpg', help_text='Upload a flyer for the event', upload_to='event_flyers/')),
                ('location', models.CharField(help_text='Enter the location of the event', max_length=300)),
                ('date', models.DateField(help_text='Enter the start date of the event')),
                ('days', models.IntegerField(default=1, help_text='Number of days the event lasts')),
                ('start_time', models.TimeField(blank=True, help_text='Enter the start time of the event', null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Live_stream',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Enter the title of the live stream', max_length=200)),
                ('description', models.CharField(help_text='Enter a brief description of the live stream', max_length=700)),
                ('stream_link', models.URLField(default='https://www.youtube.com/watch?v=sjkrrmBnpGE&t=11s', help_text='Enter the stream link of the live stream')),
                ('status', models.CharField(choices=[('live', 'Live'), ('upcoming', 'Upcoming'), ('past', 'Past')], default='upcoming', help_text='Status of the live stream', max_length=10)),
                ('reactions', models.IntegerField(default=0, help_text='Number of reactions for this live stream')),
                ('comments', models.TextField(blank=True, help_text='Comments on the live stream')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Prayer_request',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Enter your name here', max_length=200)),
                ('subject', models.TextField(help_text='Enter the content of your prayer request')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reflection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Enter your name here', max_length=200)),
                ('content', models.TextField(help_text='Enter the content of the reflection')),
                ('likes', models.IntegerField(default=0, help_text='Number of likes for this reflection')),
                ('comments', models.TextField(blank=True, help_text='Comments on the reflection')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Enter the name of the resource', max_length=300)),
                ('purchase_link', models.URLField(help_text='Enter the purchase link of the resource')),
                ('price', models.DecimalField(decimal_places=2, help_text='Enter the price of the resource', max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='Devotion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Enter the title of the devotional', max_length=200)),
                ('Bible_verse', models.JSONField(default=dict, help_text="Enter the Bible verse as a JSON object with 'reference' and 'verse_content'")),
                ('content', models.TextField(help_text='Enter the content of the devotional')),
                ('thumbnail', models.ImageField(default='devotion_thumbnails/default_devotion_thumbnail.jpg', help_text='Upload a thumbnail for the devotional', upload_to='devotion_thumbnails/')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('reflection', models.ManyToManyField(blank=True, help_text='Add reflections for this devotional', related_name='devotion_reflections', to='api.reflection')),
            ],
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Enter the title of the series', max_length=200)),
                ('description', models.CharField(help_text='Enter a brief description of the series', max_length=700)),
                ('image', models.ImageField(default='series_images/default_profile.jpg', help_text='Upload an image for the series', upload_to='series_images/')),
                ('likes', models.IntegerField(default=0, help_text='Number of likes for this Series')),
                ('date', models.DateTimeField(auto_now_add=True, help_text='Date the series was created')),
                ('thoughts', models.ManyToManyField(blank=True, help_text='Add thoughts on this series', related_name='series_thoughts', to='api.reflection')),
            ],
            options={
                'verbose_name_plural': 'Series',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Sermon',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Enter the title of the sermon', max_length=200)),
                ('description', models.CharField(help_text='Enter a brief description of the sermon', max_length=700)),
                ('video_link', models.URLField(default='https://www.youtube.com/watch?v=sjkrrmBnpGE&t=11s', help_text='Enter the video link of the sermon')),
                ('preacher', models.CharField(default='Pastor Obed Agyiri', help_text='Enter the name of the preacher', max_length=100)),
                ('podcast_link', models.URLField(blank=True, help_text='Enter the podcast link of the sermon')),
                ('likes', models.IntegerField(default=0, help_text='Number of likes for this reflection')),
                ('comments', models.TextField(blank=True, help_text='Comments on the reflection')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('resource', models.ForeignKey(help_text='Enter any additional resources for the sermon', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sermon', to='api.resource')),
                ('series', models.ForeignKey(help_text='Select the series this sermon belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sermon_series', to='api.series')),
            ],
        ),
        migrations.AddField(
            model_name='series',
            name='available_sermons',
            field=models.ManyToManyField(blank=True, help_text='Select sermons that belong to this series', related_name='series_sermons', to='api.sermon'),
        ),
    ]
