# Generated by Django 5.2.6 on 2025-10-25 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devotion',
            name='thumbnail',
            field=models.ImageField(default='https://www.freepik.com/free-photo/young-woman-being-spiritual-home_12690260.htm', help_text='Upload a thumbnail for the devotional', upload_to='devotion_thumbnails/'),
        ),
        migrations.AlterField(
            model_name='event',
            name='flyer',
            field=models.ImageField(default='https://www.freepik.com/free-photo/empty-christian-church-building_144641216.htm#fromView=search&page=1&position=1&uuid=7df8b822-77d5-4328-b319-154627617e08&query=church', help_text='Upload a flyer for the event', upload_to='event_flyers/'),
        ),
        migrations.AlterField(
            model_name='series',
            name='image',
            field=models.ImageField(default='https://www.freepik.com/free-photo/woman-praying-her-loved-ones_12690245.htm#fromView=search&page=1&position=49&uuid=b8c3c77b-8227-4daf-b533-f58011aa9874&query=bible+studies', help_text='Upload an image for the series', upload_to='series_images/'),
        ),
    ]
