# Generated by Django 5.2.6 on 2025-09-17 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=700)),
                ('flyer', models.URLField(default='https://www.freeiconspng.com/thumbs/no-image-icon/no-image-icon-15.png')),
                ('location', models.CharField(max_length=300)),
                ('date', models.DateTimeField()),
                ('days', models.IntegerField(default=1, help_text='Number of days the event lasts')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('slug', models.SlugField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('purchase_link', models.URLField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=700)),
                ('image', models.ImageField(default='https://www.freeiconspng.com/thumbs/no-image-icon/no-image-icon-15.png', upload_to='../series_images/')),
                ('slug', models.SlugField(unique=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Series',
            },
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.RenameField(
            model_name='sermon',
            old_name='date_added',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='sermon',
            old_name='url',
            new_name='podcast_link',
        ),
        migrations.AddField(
            model_name='sermon',
            name='preacher',
            field=models.CharField(default='Pastor Obed Agyiri', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sermon',
            name='video_link',
            field=models.URLField(default='https://www.youtube.com/watch?v=sjkrrmBnpGE&t=11s'),
        ),
        migrations.AddField(
            model_name='resource',
            name='sermon',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='api.sermon'),
        ),
        migrations.AddField(
            model_name='sermon',
            name='series',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sermons', to='api.series'),
        ),
    ]
