# Generated by Django 5.2.6 on 2025-09-17 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_event_resource_series_delete_book_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='title',
        ),
        migrations.AddField(
            model_name='event',
            name='end_date',
            field=models.DateTimeField(blank=True, help_text='Enter the end date of the event', null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='name',
            field=models.CharField(default='Congregational meeting', help_text='Enter the name of the event', max_length=200),
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(help_text='Enter the start date of the event'),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.CharField(help_text='Enter a brief description of the event', max_length=700),
        ),
        migrations.AlterField(
            model_name='event',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='flyer',
            field=models.ImageField(default='event_flyers/default_profile.jpg', help_text='Upload a flyer for the event', upload_to='event_flyers/'),
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(help_text='Enter the location of the event', max_length=300),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.TimeField(blank=True, help_text='Enter the start time of the event', null=True),
        ),
        migrations.AlterField(
            model_name='resource',
            name='name',
            field=models.CharField(help_text='Enter the name of the resource', max_length=300),
        ),
        migrations.AlterField(
            model_name='resource',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Enter the price of the resource', max_digits=8),
        ),
        migrations.AlterField(
            model_name='resource',
            name='purchase_link',
            field=models.URLField(help_text='Enter the purchase link of the resource'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='sermon',
            field=models.ForeignKey(help_text='Select the sermon this resource is associated with', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='api.sermon'),
        ),
        migrations.AlterField(
            model_name='series',
            name='description',
            field=models.CharField(help_text='Enter a brief description of the series', max_length=700),
        ),
        migrations.AlterField(
            model_name='series',
            name='image',
            field=models.ImageField(default='../series_images/WhatsApp_Image_2024-03-06_at_20.16.33_424dfe04.jpg', help_text='Upload an image for the series', upload_to='../series_images/'),
        ),
        migrations.AlterField(
            model_name='series',
            name='slug',
            field=models.SlugField(help_text='Enter a unique slug for the series', unique=True),
        ),
        migrations.AlterField(
            model_name='series',
            name='title',
            field=models.CharField(help_text='Enter the title of the series', max_length=200),
        ),
        migrations.AlterField(
            model_name='sermon',
            name='description',
            field=models.CharField(help_text='Enter a brief description of the sermon', max_length=700),
        ),
        migrations.AlterField(
            model_name='sermon',
            name='podcast_link',
            field=models.URLField(default='https://www.youtube.com/watch?v=sjkrrmBnpGE&t=11s', help_text='Enter the podcast link of the sermon'),
        ),
        migrations.AlterField(
            model_name='sermon',
            name='preacher',
            field=models.CharField(default='Pastor Obed Agyiri', help_text='Enter the name of the preacher', max_length=100),
        ),
        migrations.AlterField(
            model_name='sermon',
            name='series',
            field=models.ForeignKey(help_text='Select the series this sermon belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sermons', to='api.series'),
        ),
        migrations.AlterField(
            model_name='sermon',
            name='title',
            field=models.CharField(help_text='Enter the title of the sermon', max_length=200),
        ),
        migrations.AlterField(
            model_name='sermon',
            name='video_link',
            field=models.URLField(default='https://www.youtube.com/watch?v=sjkrrmBnpGE&t=11s', help_text='Enter the video link of the sermon'),
        ),
    ]
