# Generated by Django 5.2.6 on 2025-09-17 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_event_title_event_end_date_event_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='end_date',
        ),
    ]
