# Generated by Django 5.2.6 on 2025-10-28 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_devotion_reflection_reflection_devotion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reflection',
            name='devotion',
            field=models.ForeignKey(null=True, help_text='Select the devotion this reflection belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='reflections', to='api.devotion'),
        ),
    ]
