# Generated by Django 5.2.6 on 2025-09-17 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_event_end_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='series',
            name='slug',
        ),
    ]
