# Generated by Django 5.2.6 on 2025-10-28 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_reflection_devotion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reflection',
            name='devotion',
            field=models.ForeignKey(help_text='Select the devotion this reflection belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reflections', to='api.devotion'),
        ),
    ]
