# Generated by Django 5.2.6 on 2025-09-17 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_event_slug_remove_series_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='image',
            field=models.ImageField(default='series_images/WhatsApp_Image_2024-03-06_at_20.16.33_424dfe04.jpg', help_text='Upload an image for the series', upload_to='series_images/'),
        ),
    ]
