# Generated by Django 5.2.6 on 2025-09-17 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_series_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='sermon',
        ),
        migrations.AddField(
            model_name='sermon',
            name='resource',
            field=models.ForeignKey(help_text='Enter any additional resources for the sermon', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sermon', to='api.resource'),
        ),
    ]
