# Generated by Django 5.2.6 on 2025-10-28 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_reflection_devotion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devotion',
            name='thumbnail',
            field=models.ImageField(help_text='Upload a thumbnail for the devotional', null=True, upload_to='devotion_thumbnails/'),
        ),
    ]
