# Generated by Django 5.2.6 on 2025-10-29 15:05

import django.db.models.deletion
from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_devotion_thumbnail'),
    ]

    def set_default_devotion(apps, schema_editor):
        Devotion = apps.get_model('api', 'Devotion')
        Reflection = apps.get_model('api', 'Reflection')
        # Create a placeholder devotion to attach orphan reflections
        placeholder, _ = Devotion.objects.get_or_create(
            title='Placeholder Devotion',
            defaults={
                'Bible_verse': {},
                'content': 'Auto-created to satisfy NOT NULL constraint for existing reflections',
                'thumbnail': None,
                'date': timezone.now(),
            },
        )
        Reflection.objects.filter(devotion__isnull=True).update(devotion=placeholder)

    def noop(apps, schema_editor):
        pass

    operations = [
        migrations.AlterField(
            model_name='live_stream',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.RunPython(set_default_devotion, reverse_code=noop),
        migrations.AlterField(
            model_name='reflection',
            name='devotion',
            field=models.ForeignKey(
                help_text='Select the devotion this reflection belongs to',
                on_delete=django.db.models.deletion.CASCADE,
                related_name='reflections',
                to='api.devotion',
                null=False,
            ),
        ),
    ]
