# Generated by Django 5.2.6 on 2025-09-18 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_resource_sermon_sermon_resource'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(help_text='Enter the start date of the event'),
        ),
    ]
