# Generated by Django 5.2.6 on 2025-09-25 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_event_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='series',
            name='date',
        ),
        migrations.RemoveField(
            model_name='series',
            name='image',
        ),
        migrations.AddField(
            model_name='series',
            name='available_sermons',
            field=models.ManyToManyField(blank=True, help_text='Select sermons that belong to this series', related_name='series_sermons', to='api.sermon'),
        ),
    ]
