# Generated by Django 5.2.6 on 2025-09-25 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_series_date_remove_series_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sermon',
            name='series',
        ),
    ]
