# Generated by Django 5.2.6 on 2025-11-21 11:40

import datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0009_alter_reflection_devotion"),
    ]

    operations = [
        migrations.CreateModel(
            name="GalleryImage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Enter the title of the gallery image", max_length=200
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        help_text="Upload the gallery image",
                        upload_to="gallery_images/",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        help_text="Enter a brief description of the gallery image",
                        max_length=700,
                    ),
                ),
                ("date", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name="devotion",
            name="date",
            field=models.DateTimeField(
                default=datetime.datetime.now,
                help_text="Date the devotional was created",
            ),
        ),
    ]
