# Generated by Django 5.2.6 on 2025-09-25 14:02

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_sermon_series'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='Date the series was created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sermon',
            name='series',
            field=models.ForeignKey(help_text='Select the series this sermon belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sermon_series', to='api.series'),
        ),
    ]
