# Generated by Django 5.2.6 on 2025-11-21 12:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0010_galleryimage_alter_devotion_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="galleryimage",
            name="venue",
            field=models.CharField(
                blank=True,
                help_text="Enter the venue where the image was taken",
                max_length=300,
            ),
        ),
    ]
