# Generated by Django 5.2.6 on 2025-12-05 13:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0011_galleryimage_venue"),
    ]

    operations = [
        migrations.AddField(
            model_name="galleryimage",
            name="likes",
            field=models.IntegerField(
                default=0, help_text="Number of likes for this gallery image"
            ),
        ),
    ]
