# Generated by Django 5.2.6 on 2025-09-25 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_series_date_sermon_series'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='image',
            field=models.ImageField(default='series_images/default_series.jpg', help_text='Upload an image for the series', upload_to='series_images/'),
        ),
    ]
