# Generated by Django 5.2.6 on 2026-05-13 14:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0012_galleryimage_likes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="devotion",
            name="thumbnail",
            field=models.ImageField(
                help_text="Upload a thumbnail for the devotional",
                max_length=500,
                null=True,
                upload_to="devotion_thumbnails/",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="flyer",
            field=models.ImageField(
                default="https://www.freepik.com/free-photo/empty-christian-church-building_144641216.htm#fromView=search&page=1&position=1&uuid=7df8b822-77d5-4328-b319-154627617e08&query=church",
                help_text="Upload a flyer for the event",
                max_length=500,
                upload_to="event_flyers/",
            ),
        ),
        migrations.AlterField(
            model_name="galleryimage",
            name="image",
            field=models.ImageField(
                help_text="Upload the gallery image",
                max_length=500,
                upload_to="gallery_images/",
            ),
        ),
        migrations.AlterField(
            model_name="series",
            name="image",
            field=models.ImageField(
                default="https://www.freepik.com/free-photo/woman-praying-her-loved-ones_12690245.htm#fromView=search&page=1&position=49&uuid=b8c3c77b-8227-4daf-b533-f58011aa9874&query=bible+studies",
                help_text="Upload an image for the series",
                max_length=500,
                upload_to="series_images/",
            ),
        ),
    ]
