# Generated by Django 5.2.6 on 2025-09-26 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_series_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='series',
            options={'ordering': ['-date'], 'verbose_name_plural': 'Series'},
        ),
        migrations.AlterField(
            model_name='series',
            name='image',
            field=models.ImageField(default='series_images/default_profile.jpg', help_text='Upload an image for the series', upload_to='series_images/'),
        ),
    ]
