# Generated by Django 5.2.6 on 2026-05-13 16:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0013_alter_devotion_thumbnail_alter_event_flyer_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ContributionChannel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Display name for the receiving account",
                        max_length=120,
                    ),
                ),
                (
                    "channel_type",
                    models.CharField(
                        choices=[("momo", "MOMO"), ("bank", "BANK")],
                        help_text="Contribution channel type",
                        max_length=10,
                    ),
                ),
                (
                    "account_name",
                    models.CharField(help_text="Account holder name", max_length=200),
                ),
                (
                    "account_number",
                    models.CharField(
                        help_text="MOMO number or bank account number", max_length=120
                    ),
                ),
                (
                    "bank_name",
                    models.CharField(
                        blank=True,
                        help_text="Bank name (for bank channels)",
                        max_length=150,
                    ),
                ),
                (
                    "branch",
                    models.CharField(
                        blank=True, help_text="Bank branch (optional)", max_length=150
                    ),
                ),
                (
                    "network",
                    models.CharField(
                        blank=True,
                        help_text="MOMO network (for MOMO channels)",
                        max_length=100,
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="GHS",
                        help_text="Currency code, e.g. GHS",
                        max_length=10,
                    ),
                ),
                (
                    "instructions",
                    models.TextField(
                        blank=True, help_text="Optional guidance shown to contributors"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this receiving account is currently active",
                    ),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(
                        default=0, help_text="Sort order for displaying channels"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["display_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="ContributionIntent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Amount contributor sent",
                        max_digits=10,
                    ),
                ),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("tithe", "Tithe"),
                            ("offering", "Offering"),
                            ("project", "Project"),
                            ("donation", "Donation"),
                            ("other", "Other"),
                        ],
                        default="donation",
                        max_length=20,
                    ),
                ),
                (
                    "donor_name",
                    models.CharField(
                        blank=True,
                        help_text="Contributor name (optional)",
                        max_length=200,
                    ),
                ),
                (
                    "donor_phone",
                    models.CharField(
                        blank=True,
                        help_text="Contributor phone (optional)",
                        max_length=30,
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        blank=True,
                        help_text="Bank/MOMO transfer reference",
                        max_length=120,
                    ),
                ),
                (
                    "proof_url",
                    models.URLField(
                        blank=True, help_text="Optional proof screenshot URL"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("confirmed", "Confirmed"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "admin_note",
                    models.TextField(
                        blank=True, help_text="Internal note by admin/staff"
                    ),
                ),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "channel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="intents",
                        to="api.contributionchannel",
                    ),
                ),
                (
                    "confirmed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="confirmed_contribution_intents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Reel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("caption", models.TextField(blank=True)),
                (
                    "video_url",
                    models.URLField(help_text="Publicly accessible reel video URL"),
                ),
                (
                    "thumbnail_url",
                    models.URLField(
                        blank=True, help_text="Optional reel thumbnail image URL"
                    ),
                ),
                ("category", models.CharField(blank=True, max_length=100)),
                ("is_published", models.BooleanField(default=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("views_count", models.PositiveIntegerField(default=0)),
                ("likes_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_reels",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-published_at", "-created_at"],
            },
        ),
    ]
