# Generated by Django 5.2.6 on 2025-10-11 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_series_options_alter_series_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Devotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter the title of the devotional', max_length=200)),
                ('Bible_verse', models.CharField(help_text='Enter the Bible verse for the devotional', max_length=300)),
                ('content', models.TextField(help_text='Enter the content of the devotional')),
                ('thumbnail', models.ImageField(default='devotion_thumbnails/default_devotion_thumbnail.jpg', help_text='Upload a thumbnail for the devotional', upload_to='devotion_thumbnails/')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
