# Generated by Django 5.2.6 on 2025-10-11 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_devotion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reflection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter your name here', max_length=200)),
                ('email', models.EmailField(help_text='Enter your email here', max_length=254)),
                ('content', models.TextField(help_text='Enter the content of the reflection')),
                ('likes', models.IntegerField(default=0, help_text='Number of likes for this reflection')),
                ('comments', models.TextField(blank=True, help_text='Comments on the reflection')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='series',
            name='likes',
            field=models.IntegerField(default=0, help_text='Number of likes for this Series'),
        ),
        migrations.AddField(
            model_name='sermon',
            name='comments',
            field=models.TextField(blank=True, help_text='Comments on the reflection'),
        ),
        migrations.AddField(
            model_name='sermon',
            name='likes',
            field=models.IntegerField(default=0, help_text='Number of likes for this reflection'),
        ),
        migrations.AddField(
            model_name='devotion',
            name='reflection',
            field=models.ManyToManyField(blank=True, help_text='Add reflections for this devotional', related_name='devotion_reflections', to='api.reflection'),
        ),
        migrations.AddField(
            model_name='series',
            name='thoughts',
            field=models.ManyToManyField(blank=True, help_text='Add thoughts on this series', related_name='series_thoughts', to='api.reflection'),
        ),
    ]
