# Generated by Django 5.2.6 on 2026-05-13 16:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0014_contributionchannel_contributionintent_reel"),
    ]

    operations = [
        migrations.CreateModel(
            name="Gallery",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Enter the title of the gallery", max_length=200
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        help_text="Enter a brief description of the gallery",
                        max_length=700,
                    ),
                ),
                (
                    "venue",
                    models.CharField(
                        blank=True,
                        help_text="Enter the venue where the images were taken",
                        max_length=300,
                    ),
                ),
                (
                    "likes",
                    models.IntegerField(
                        default=0, help_text="Number of likes for this gallery"
                    ),
                ),
                ("date", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "Galleries",
                "ordering": ["-date"],
            },
        ),
        migrations.AddField(
            model_name="galleryimage",
            name="gallery",
            field=models.ForeignKey(
                blank=True,
                help_text="Select the gallery this image belongs to",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="api.gallery",
            ),
        ),
    ]
