# Generated by Django 5.2.6 on 2025-10-15 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_reflection_series_likes_sermon_comments_sermon_likes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='prayer_request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter your name here', max_length=200)),
                ('subject', models.TextField(help_text='Enter the content of your prayer request')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='reflection',
            name='email',
        ),
    ]
