# Generated by Django 5.2.6 on 2026-05-14 14:28

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0015_gallery_galleryimage_gallery"),
    ]

    operations = [
        migrations.CreateModel(
            name="PageConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(max_length=100, unique=True)),
                ("title", models.CharField(max_length=180)),
                ("subtitle", models.CharField(blank=True, max_length=260)),
                ("body", models.TextField(blank=True)),
                ("hero_image_url", models.URLField(blank=True)),
                ("seo_title", models.CharField(blank=True, max_length=180)),
                ("seo_description", models.CharField(blank=True, max_length=320)),
                ("is_enabled", models.BooleanField(default=True)),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["display_order", "slug"],
            },
        ),
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.PositiveSmallIntegerField(
                        default=1, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "church_name",
                    models.CharField(default="Grace Cathedral", max_length=120),
                ),
                (
                    "tagline",
                    models.CharField(
                        default="A community of faith, hope, and love.", max_length=280
                    ),
                ),
                ("logo_url", models.URLField(blank=True)),
                ("banner_image_url", models.URLField(blank=True)),
                ("phone", models.CharField(blank=True, max_length=40)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("address", models.CharField(blank=True, max_length=300)),
                (
                    "service_times",
                    models.JSONField(
                        default=list, help_text="List of service time strings"
                    ),
                ),
                (
                    "social_links",
                    models.JSONField(
                        default=dict, help_text="Map of social platform -> URL"
                    ),
                ),
                (
                    "footer_note",
                    models.CharField(
                        blank=True,
                        default="Made with care for our community.",
                        max_length=220,
                    ),
                ),
                ("default_seo_title", models.CharField(blank=True, max_length=180)),
                (
                    "default_seo_description",
                    models.CharField(blank=True, max_length=320),
                ),
                ("default_og_image_url", models.URLField(blank=True)),
                ("show_announcements", models.BooleanField(default=True)),
                ("show_gallery", models.BooleanField(default=True)),
                ("show_resources", models.BooleanField(default=True)),
                ("show_prayer_request", models.BooleanField(default=True)),
                ("show_live_badge", models.BooleanField(default=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="ThemeSettings",
            fields=[
                (
                    "id",
                    models.PositiveSmallIntegerField(
                        default=1, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("primary_color", models.CharField(default="#8B5A2B", max_length=20)),
                ("secondary_color", models.CharField(default="#F5F1EA", max_length=20)),
                ("accent_color", models.CharField(default="#3B82F6", max_length=20)),
                ("text_color", models.CharField(default="#1F2937", max_length=20)),
                (
                    "background_color",
                    models.CharField(default="#FFFFFF", max_length=20),
                ),
                ("border_color", models.CharField(default="#E5E7EB", max_length=20)),
                (
                    "heading_font",
                    models.CharField(blank=True, default="Fraunces", max_length=120),
                ),
                (
                    "body_font",
                    models.CharField(blank=True, default="Inter", max_length=120),
                ),
                ("button_style", models.CharField(default="filled", max_length=20)),
                ("card_radius", models.PositiveSmallIntegerField(default=16)),
                ("button_radius", models.PositiveSmallIntegerField(default=12)),
                ("shadow_strength", models.CharField(default="medium", max_length=20)),
                (
                    "layout_density",
                    models.CharField(default="comfortable", max_length=20),
                ),
                ("section_spacing", models.CharField(default="medium", max_length=20)),
                ("dark_mode_enabled", models.BooleanField(default=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="NavigationItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("label", models.CharField(max_length=120)),
                ("url", models.CharField(blank=True, max_length=300)),
                (
                    "item_type",
                    models.CharField(
                        choices=[("link", "Link"), ("dropdown", "Dropdown")],
                        default="link",
                        max_length=20,
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        choices=[("header", "Header"), ("footer", "Footer")],
                        default="header",
                        max_length=20,
                    ),
                ),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("is_enabled", models.BooleanField(default=True)),
                ("open_in_new_tab", models.BooleanField(default=False)),
                (
                    "cta_style",
                    models.CharField(
                        choices=[
                            ("none", "None"),
                            ("primary", "Primary"),
                            ("outline", "Outline"),
                            ("ghost", "Ghost"),
                        ],
                        default="none",
                        max_length=20,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="api.navigationitem",
                    ),
                ),
            ],
            options={
                "ordering": ["location", "display_order", "label"],
            },
        ),
        migrations.CreateModel(
            name="SectionConfig",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "key",
                    models.SlugField(
                        help_text="Stable section identifier, e.g. home-hero",
                        max_length=120,
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=180)),
                ("subtitle", models.CharField(blank=True, max_length=260)),
                ("body", models.TextField(blank=True)),
                ("cta_label", models.CharField(blank=True, max_length=120)),
                ("cta_url", models.CharField(blank=True, max_length=300)),
                ("background_image_url", models.URLField(blank=True)),
                (
                    "overlay_opacity",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.2,
                        max_digits=3,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1),
                        ],
                    ),
                ),
                (
                    "text_align",
                    models.CharField(
                        choices=[
                            ("left", "Left"),
                            ("center", "Center"),
                            ("right", "Right"),
                        ],
                        default="left",
                        max_length=20,
                    ),
                ),
                ("is_enabled", models.BooleanField(default=True)),
                ("display_order", models.PositiveIntegerField(default=0)),
                (
                    "extra",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Optional additional options",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="api.pageconfig",
                    ),
                ),
            ],
            options={
                "ordering": ["page__slug", "display_order", "key"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("page", "key"), name="unique_section_key_per_page"
                    )
                ],
            },
        ),
    ]
