# Generated by Django 5.2.6 on 2026-05-14 14:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0016_pageconfig_sitesettings_themesettings_navigationitem_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="prayer_request",
            name="phone_contact",
            field=models.CharField(
                blank=True,
                help_text="Optional phone number for follow-up",
                max_length=30,
            ),
        ),
    ]
