# Generated by Django 5.2.6 on 2025-10-15 23:46

from django.db import migrations, models
import uuid


def populate_uuids(apps, schema_editor):
    # Get model classes
    Sermon = apps.get_model('api', 'Sermon')
    Resource = apps.get_model('api', 'Resource')
    Series = apps.get_model('api', 'Series')
    Event = apps.get_model('api', 'Event')
    Devotion = apps.get_model('api', 'Devotion')
    Reflection = apps.get_model('api', 'Reflection')
    Prayer_request = apps.get_model('api', 'Prayer_request')
    Announcement = apps.get_model('api', 'Announcement')

    # Populate UUIDs for existing records
    for model in [Sermon, Resource, Series, Event, Devotion, Reflection, Prayer_request, Announcement]:
        for obj in model.objects.all():
            obj.uuid_id = uuid.uuid4()
            obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_announcement_alter_devotion_id_alter_event_id_and_more'),
    ]

    operations = [
        # Add UUID fields
        migrations.AddField(
            model_name='announcement',
            name='uuid_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='devotion',
            name='uuid_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='event',
            name='uuid_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='prayer_request',
            name='uuid_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='reflection',
            name='uuid_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='resource',
            name='uuid_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='series',
            name='uuid_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='sermon',
            name='uuid_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        # Populate UUIDs for existing data
        migrations.RunPython(populate_uuids, migrations.RunPython.noop),
        # Remove old primary key fields
        migrations.RemoveField(
            model_name='announcement',
            name='id',
        ),
        migrations.RemoveField(
            model_name='devotion',
            name='id',
        ),
        migrations.RemoveField(
            model_name='event',
            name='id',
        ),
        migrations.RemoveField(
            model_name='prayer_request',
            name='id',
        ),
        migrations.RemoveField(
            model_name='reflection',
            name='id',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='id',
        ),
        migrations.RemoveField(
            model_name='series',
            name='id',
        ),
        migrations.RemoveField(
            model_name='sermon',
            name='id',
        ),
        # Rename UUID fields to 'id'
        migrations.RenameField(
            model_name='announcement',
            old_name='uuid_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='devotion',
            old_name='uuid_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='uuid_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='prayer_request',
            old_name='uuid_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='reflection',
            old_name='uuid_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='resource',
            old_name='uuid_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='series',
            old_name='uuid_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='sermon',
            old_name='uuid_id',
            new_name='id',
        ),
        # Set primary key constraint
        migrations.AlterField(
            model_name='announcement',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='devotion',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='prayer_request',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='reflection',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='resource',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='series',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sermon',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
