# Generated by Django 5.2.6 on 2026-05-15 20:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0017_prayer_request_phone_contact"),
    ]

    operations = [
        migrations.AlterField(
            model_name="devotion",
            name="thumbnail",
            field=models.URLField(
                blank=True,
                help_text="Enter a thumbnail URL for the devotional",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="flyer",
            field=models.URLField(
                default="https://www.freepik.com/free-photo/empty-christian-church-building_144641216.htm#fromView=search&page=1&position=1&uuid=7df8b822-77d5-4328-b319-154627617e08&query=church",
                help_text="Enter a flyer URL for the event",
            ),
        ),
        migrations.AlterField(
            model_name="galleryimage",
            name="image",
            field=models.URLField(help_text="Enter the gallery image URL"),
        ),
        migrations.AlterField(
            model_name="series",
            name="image",
            field=models.URLField(
                default="https://www.freepik.com/free-photo/woman-praying-her-loved-ones_12690245.htm#fromView=search&page=1&position=49&uuid=b8c3c77b-8227-4daf-b533-f58011aa9874&query=bible+studies",
                help_text="Enter an image URL for the series",
            ),
        ),
    ]
