# Generated by Django 5.2.6 on 2025-10-16 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20251015_2346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devotion',
            name='Bible_verse',
            field=models.JSONField(default=dict, help_text="Enter the Bible verse as a JSON object with 'reference' and 'verse_content'"),
        ),
    ]
