# Generated by Django 5.2.6 on 2026-05-18 15:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0018_alter_devotion_thumbnail_alter_event_flyer_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BiblePassageCache",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        help_text="Bible reference, e.g. 'John 3:16'", max_length=200
                    ),
                ),
                (
                    "translation",
                    models.CharField(
                        default="kjv",
                        help_text="Bible translation code, e.g. 'kjv'",
                        max_length=50,
                    ),
                ),
                (
                    "passage_text",
                    models.TextField(
                        blank=True, help_text="The fetched Bible passage text"
                    ),
                ),
                (
                    "raw_response",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Raw response returned from the Bible API",
                    ),
                ),
                (
                    "fetched_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when the passage was last fetched",
                    ),
                ),
            ],
            options={
                "ordering": ["-fetched_at"],
                "unique_together": {("reference", "translation")},
            },
        ),
    ]
