# Generated by Django 5.2.6 on 2025-10-17 00:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_devotion_bible_verse'),
    ]

    operations = [
        migrations.CreateModel(
            name='Live_stream',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Enter the title of the live stream', max_length=200)),
                ('description', models.CharField(help_text='Enter a brief description of the live stream', max_length=700)),
                ('stream_link', models.URLField(default='https://www.youtube.com/watch?v=sjkrrmBnpGE&t=11s', help_text='Enter the stream link of the live stream')),
                ('status', models.CharField(choices=[('live', 'Live'), ('upcoming', 'Upcoming'), ('past', 'Past')], default='upcoming', help_text='Status of the live stream', max_length=10)),
                ('reactions', models.IntegerField(default=0, help_text='Number of reactions for this live stream')),
                ('comments', models.TextField(blank=True, help_text='Comments on the live stream')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='sermon',
            name='podcast_link',
            field=models.URLField(blank=True, help_text='Enter the podcast link of the sermon'),
        ),
    ]
