# Generated by Django 5.2.6 on 2026-05-20 21:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0019_biblepassagecache"),
    ]

    operations = [
        migrations.AddField(
            model_name="resource",
            name="category",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Enter the category of the resource, e.g. book, soap, cream",
                max_length=120,
            ),
        ),
        migrations.AddField(
            model_name="resource",
            name="description",
            field=models.TextField(
                blank=True, default="", help_text="Enter a description of the resource"
            ),
        ),
        migrations.AddField(
            model_name="resource",
            name="image_url",
            field=models.URLField(
                blank=True, default="", help_text="Enter an image URL for the resource"
            ),
        ),
        migrations.AddField(
            model_name="resource",
            name="is_available",
            field=models.BooleanField(
                default=True,
                help_text="Whether the resource is currently available for purchase",
            ),
        ),
    ]
